# Generated by Django 4.2 on 2023-10-09 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'サイト', 'verbose_name_plural': 'サイト'},
        ),
        migrations.RemoveField(
            model_name='item',
            name='sample_10',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sample_2',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sample_7',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sample_8',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sample_9',
        ),
        migrations.AddField(
            model_name='item',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='添付画像'),
        ),
        migrations.AddField(
            model_name='item',
            name='memo',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='コメント欄'),
        ),
        migrations.AddField(
            model_name='item',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ラーメン店'),
        ),
        migrations.AddField(
            model_name='item',
            name='name1',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='メニュー名称'),
        ),
        migrations.AddField(
            model_name='item',
            name='name2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='都道府県'),
        ),
        migrations.AddField(
            model_name='item',
            name='name3',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='市区町村'),
        ),
        migrations.AddField(
            model_name='item',
            name='sample_cost',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='値段'),
        ),
        migrations.AddField(
            model_name='item',
            name='sample_menhutosa',
            field=models.IntegerField(blank=True, choices=[(1, '極細麺(1.1mm)'), (2, '細麺(1.15mm)'), (3, '中細麺(1.25mm)'), (4, '中太麺(1.4mm)'), (5, '太麺(1.7〜1.875mm)'), (6, '極太麺(2.2〜2.5mm)')], null=True, verbose_name='麺の太さ'),
        ),
        migrations.AddField(
            model_name='item',
            name='sample_satisfaction',
            field=models.IntegerField(blank=True, null=True, verbose_name='満足度評価'),
        ),
        migrations.AddField(
            model_name='item',
            name='sample_url',
            field=models.URLField(blank=True, max_length=100, null=True, verbose_name='ホームページ'),
        ),
        migrations.AlterField(
            model_name='item',
            name='sample_1',
            field=models.TextField(blank=True, choices=[('醤油', '醤油'), ('塩', '塩'), ('豚骨', '豚骨'), ('味噌', '味噌'), ('鯛', '鯛'), ('鶏白湯', '鶏白湯'), ('つけ麺', 'つけ麺'), ('担々麺', '担々麺'), ('油そば', '油そば')], null=True, verbose_name='味'),
        ),
        migrations.AlterField(
            model_name='item',
            name='sample_3',
            field=models.IntegerField(blank=True, null=True, verbose_name='こってり度評価'),
        ),
        migrations.AlterField(
            model_name='item',
            name='sample_4',
            field=models.IntegerField(blank=True, null=True, verbose_name='からさ評価'),
        ),
        migrations.AlterField(
            model_name='item',
            name='sample_5',
            field=models.IntegerField(blank=True, null=True, verbose_name='値段評価'),
        ),
        migrations.AlterField(
            model_name='item',
            name='sample_6',
            field=models.IntegerField(blank=True, null=True, verbose_name='アクセス評価'),
        ),
    ]
